# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: ":boom: Breaking Changes"
      labels: 
        - breaking-change

    - title: ":wrench: Build"
      labels:
        - build
  
    - title: ":boar: Chore"
      labels:
        - chore
  
    - title: ":sparkles: New Features"
      labels:
        - new-feature
        - enhancement
  
    - title: ":zap: Performance"
      labels:
        - performance"
  
    - title: ":recycle: Refactor"
      labels:
        - refactor
  
    - title: ":bug: Bug Fixes"
      labels:
        - bug
        - fix
  
    - title: ":white_check_mark: Test"
      labels:
        - test
  
    - title: ":arrow_up: Dependency Updates"
      labels:
        - dependencies
      collapse-after: 1
