name: Nuova feature youPark
description: Richiedi una nuova feature per youPark.
title: "[FEATURE]: "
labels: [enhancement]
projects: ["Viatron/21"]
body:
  - type: textarea
    id: who
    attributes:
      label: In qualità di
      description: Indica qui il o gli utenti interessati da questa feature
      placeholder: utente o utenti attori della storia
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Vorrei
      description: Spiega cosa vorrebbero o dovrebbero poter fare il o gli utenti indicati sopra
      placeholder: Descrivi cosa vorresti fare come utente
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Al fine di
      description: Elenco dei benefici che apporta la feature
      placeholder: Spiega quali sono i vantaggi e motivi che spingo il o gli utenti a voler fare le azioni spiegate prima
    validations:
      required: true
  - type: textarea
    id: UAC
    attributes:
      label: Criteri di accettazione
      description: Elenca i requisiti minimi per rispondere correttamente alla esigenza esperessa sopra
      placeholder: |
        - 1° requisito/funzione
        - 2° requisito/funzione
        - 3° requisito/funzione
        - ...
    validations:
      required: true
  - type: dropdown
    id: scope
    attributes:
      label: Ambito di competenza
      options:
        - firmware impianto
        - concentratore
        - cassa manuale
        - postazione codifica abbonamenti
        - centralizzazione
        - API
    validations:
      required: true
